/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sara;

import java.util.LinkedList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Lazaro
 */
public class EquipmentReporterGUI extends javax.swing.JFrame {
private ReservationSystem resSystem;
    /**
     * Creates new form EquipmentReporterGUI
     */
//    public EquipmentReporterGUI() {
//        initComponents();
//    }
//    
    public EquipmentReporterGUI(ReservationSystem resSystem) {
        initComponents();        
        this.resSystem = resSystem;
        DamagedNo.setSelected(true);
        DamageLabel.setVisible(false);
        DescriptionField.setVisible(false);
        EqCB.removeAllItems();


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DamagedGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DamageLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        DamagedYes = new javax.swing.JRadioButton();
        DamagedNo = new javax.swing.JRadioButton();
        reportButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        searchRoomButton = new javax.swing.JButton();
        RoomField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EqCB = new javax.swing.JComboBox();
        TypeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchEquipmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SARA - Report Damaged Equipment");

        jLabel3.setText("Equipment ID");

        DamageLabel.setText("Damage Description");

        jLabel7.setText("Damaged");

        DamagedGroup.add(DamagedYes);
        DamagedYes.setText("Yes");
        DamagedYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamagedYesActionPerformed(evt);
            }
        });

        DamagedGroup.add(DamagedNo);
        DamagedNo.setText("No");
        DamagedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamagedNoActionPerformed(evt);
            }
        });

        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        searchRoomButton.setText("Search");
        searchRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRoomButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Room ID");

        EqCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EqCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EqCBMouseClicked(evt);
            }
        });
        EqCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqCBActionPerformed(evt);
            }
        });

        TypeField.setEditable(false);

        jLabel6.setText("Type");

        searchEquipmentButton.setText("Search");
        searchEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEquipmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(DamageLabel))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoomField)
                                    .addComponent(DamagedYes)
                                    .addComponent(DescriptionField))
                                .addGap(18, 18, 18)
                                .addComponent(DamagedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EqCB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(TypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchRoomButton)
                    .addComponent(searchEquipmentButton))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(reportButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(RoomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchRoomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(EqCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEquipmentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DamagedYes)
                        .addComponent(DamagedNo))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DamageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(reportButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DamagedYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamagedYesActionPerformed
        DamageLabel.setVisible(DamagedYes.isSelected());
        DescriptionField.setVisible(DamagedYes.isSelected());
    }//GEN-LAST:event_DamagedYesActionPerformed

    private void DamagedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamagedNoActionPerformed
        DamageLabel.setVisible(DamagedYes.isSelected());
        DescriptionField.setVisible(DamagedYes.isSelected());
    }//GEN-LAST:event_DamagedNoActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        if(DamagedYes.isSelected()) {
            equip.reportDamage(DescriptionField.getText());
            ReservationSystem.save(resSystem);
            JOptionPane.showMessageDialog(null, "Equipment reported successfully");
            this.dispose();
        } else {
            equip.repair();
            ReservationSystem.save(resSystem);
            JOptionPane.showMessageDialog(null, "Equipment repaired");
            this.dispose();
        }
    }//GEN-LAST:event_reportButtonActionPerformed

    private void searchRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRoomButtonActionPerformed
        try {
            room = resSystem.roomSearch(Integer.parseInt(RoomField.getText()));
            if (room == null) {
                JOptionPane.showMessageDialog(null, "Room ID Invalid");
            } else {
                EqCB.removeAllItems();
                Equipment[] equipList = room.getEquipment();
                for (int i = 0; i < 4; i++) {
                    if(equipList[i] != null) {
                        EqCB.addItem(equipList[i].getID());
                    }
                    
                    searchRoomButton.setEnabled(false);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }

    }//GEN-LAST:event_searchRoomButtonActionPerformed

    private void EqCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqCBActionPerformed

    }//GEN-LAST:event_EqCBActionPerformed

    private void EqCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqCBMouseClicked

    }//GEN-LAST:event_EqCBMouseClicked

    private void searchEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEquipmentButtonActionPerformed
        idFound = (int) EqCB.getSelectedItem();
        equip = resSystem.equipmentSearch(idFound);

        DamageLabel.setVisible(equip.getDamaged());
        DescriptionField.setVisible(equip.getDamaged());
        DamagedYes.setSelected(equip.getDamaged());
        TypeField.setText(equip.getType());
        DescriptionField.setText(equip.getDamageDescription());
    }//GEN-LAST:event_searchEquipmentButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DamageLabel;
    private javax.swing.ButtonGroup DamagedGroup;
    private javax.swing.JRadioButton DamagedNo;
    private javax.swing.JRadioButton DamagedYes;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JComboBox EqCB;
    private javax.swing.JTextField RoomField;
    private javax.swing.JTextField TypeField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton searchEquipmentButton;
    private javax.swing.JButton searchRoomButton;
    // End of variables declaration//GEN-END:variables
    private Equipment equip;
    private Room room;
    private int idFound;
}

