/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sara;

import java.io.Serializable;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Casey
 */
public class ModifyUserGUI extends javax.swing.JFrame implements Serializable{
private static ReservationSystem resSystem;
private static Requestor user;


    /**
     * Creates new form ModifyUserGUI
     */
    public ModifyUserGUI(ReservationSystem resSystem) {
        this.resSystem = resSystem;
        initComponents();
        UserNotFound.setVisible(false);
        DeleteUserButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        DepartmentField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        AddUserCancel = new javax.swing.JButton();
        DepartmentLabel = new javax.swing.JLabel();
        ModifyUserButton = new javax.swing.JButton();
        EMailField = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        FindUserButton = new javax.swing.JButton();
        CheckFaculty = new javax.swing.JCheckBox();
        AdminCheck = new javax.swing.JCheckBox();
        UserNotFound = new javax.swing.JLabel();
        DeleteUserButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PhoneField.setText("(xxx)xxx-xxxx");

        AddUserCancel.setText("Cancel");
        AddUserCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserCancelActionPerformed(evt);
            }
        });

        DepartmentLabel.setText("Department");

        ModifyUserButton.setText("Modify");
        ModifyUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyUserButtonActionPerformed(evt);
            }
        });

        PhoneLabel.setText("Phone");

        UserIDLabel.setText("UserId");

        PasswordField.setText("jPasswordField1");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SARA - Modify User");

        PasswordLabel.setText("Password");

        EmailLabel.setText("E-Mail");

        NameLabel.setText("Name");

        UserIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDFieldActionPerformed(evt);
            }
        });

        FindUserButton.setText("Find User");
        FindUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindUserButtonActionPerformed(evt);
            }
        });

        CheckFaculty.setText("Faculty Privilges");
        CheckFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFacultyActionPerformed(evt);
            }
        });

        AdminCheck.setText("Administrator");

        UserNotFound.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserNotFound.setForeground(new java.awt.Color(255, 0, 51));
        UserNotFound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNotFound.setText("User Not Found");

        DeleteUserButton.setText("Delete User");
        DeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameLabel)
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PasswordLabel)
                                .addComponent(UserIDLabel))
                            .addGap(42, 42, 42))
                        .addComponent(ModifyUserButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(PhoneLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(AddUserCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserIDField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EMailField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DepartmentField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(FindUserButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(DeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(UserNotFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DepartmentLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDLabel)
                    .addComponent(UserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindUserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNotFound, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EMailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteUserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartmentLabel)
                    .addComponent(DepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(CheckFaculty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyUserButton)
                    .addComponent(AddUserCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserCancelActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserCancelActionPerformed

    private void ModifyUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyUserButtonActionPerformed
        User user = resSystem.searchUsers(Integer.parseInt(UserIDField.getText()));
        if(AdminCheck.isSelected())
        {
        user.setName(NameField.getText());
        user.setEmail(EMailField.getText());
        user.setPassword(PasswordField.getPassword());
        user.setPrivliges(CheckFaculty.isSelected());
        user.setPhone(PhoneField.getText());
        }
        else
        {
        user.setName(NameField.getText());
        user.setEmail(EMailField.getText());
        user.setPassword(PasswordField.getPassword());
        user.setPrivliges(CheckFaculty.isSelected());
        }
        
        ReservationSystem.save(resSystem);
        JOptionPane.showMessageDialog(null, "User Modified");
        this.setVisible(false);
        
    }//GEN-LAST:event_ModifyUserButtonActionPerformed

    private void UserIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDFieldActionPerformed

    private void FindUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindUserButtonActionPerformed
        
        if(!UserIDField.getText().isEmpty()){
        if(resSystem.searchUsers(Integer.parseInt(UserIDField.getText())) == null)
        {
            UserNotFound.setVisible(true);
            NameField.setText(null);
        EMailField.setText(null);
        DepartmentField.setText(null);
        CheckFaculty.setSelected(false);
        AdminCheck.setSelected(false);
        PhoneField.setText(null);
        }
        else
        {
        User user = resSystem.searchUsers(Integer.parseInt(UserIDField.getText()));
        UserNotFound.setVisible(false);
        NameField.setText(user.getUserName());
        EMailField.setText(user.getUserEmail());
        DepartmentField.setText(user.getDepartment());
        if(user.hasPriviliges())
            CheckFaculty.setSelected(true);
        if(user instanceof Administrator)
        {
            AdminCheck.setSelected(true);
            PhoneField.setVisible(true);
            PhoneLabel.setVisible(true);
            PhoneField.setText(String.valueOf(user.getPhone()));
            DepartmentField.setText("Warrington IT");
        }
        else
        {
            AdminCheck.setVisible(false);
            PhoneField.setVisible(false);
            PhoneLabel.setVisible(false);
        }}}
        else
        JOptionPane.showMessageDialog(null, "Please enter a valid UserID");
    }//GEN-LAST:event_FindUserButtonActionPerformed

    private void CheckFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckFacultyActionPerformed

    private void DeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserButtonActionPerformed
        User user = resSystem.searchUsers(Integer.parseInt(UserIDField.getText()));
        resSystem.removeUser(user);
        JOptionPane.showMessageDialog(null, "User Removed");
        this.setVisible(false);

    }//GEN-LAST:event_DeleteUserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserCancel;
    private javax.swing.JCheckBox AdminCheck;
    private javax.swing.JCheckBox CheckFaculty;
    private javax.swing.JButton DeleteUserButton;
    private javax.swing.JTextField DepartmentField;
    private javax.swing.JLabel DepartmentLabel;
    private javax.swing.JTextField EMailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton FindUserButton;
    private javax.swing.JButton ModifyUserButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel UserNotFound;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
